### PR TITLE
added +1 all stats button

### PR DESCRIPTION
**Pull request by cantsay**
ignore all the separate commits I made, I was trying to change our code so it was consistent with yours and I KEPT STUFFING UP lol

### CODE REVIEW

**Comment by Ntonio36** [comment]
Just a question, what could be the purpose of this PR ^^" ?

**Comment by Zarel** [comment]
Convenience, I assume.

**Comment by KrisOnline** [comment]
It’s for when someone is calcingwwith s Pokemon like Victini who uses the +1 to all z-moves so you don’t have to manually do +1 in the required stats

**Comment by AustinXII** [comment]
^

**Comment by AustinXII** [comment]
Thanks!

**Pull request merged**
