### PR TITLE
Fix Struggle GSC calculation

### PR DESCRIPTION
**Pull request by Ntonio36**
According to Bulbapedia:
1) Struggle is treated as a Normal-type move in Gen I
2) It becomes "typeless" from gen 2 ownards.

We can deduce from 1) that:
- Struggle inherits all Normal-type properties including:
-- The offense/defense relationship with other types ;
-- The type category of Normal, which is Physical (it was a thing before gen IV).

### CODE REVIEW

**Comment by AustinXII** [comment]
@Marty-D

**Comment by Marty-D** [comment]
All you need to do is add the Physical category for None. Everything else you listed is handled by Struggle's type in Gen 1, which is Normal, so it behaves like any other Normal move already.

**Comment by Ntonio36** [comment]
@Marty-D good now ?

**Comment by Marty-D** [comment]
\>All you need to do is add the Physical category for None.
No.

**Comment by Ntonio36** [comment]
This time should be good.

**Comment by Marty-D** [comment]
You didn't need to add Physical to Struggle, but category handling is really inconsistent so why not.

**Pull request merged**
