### PR TITLE
Fix Photon Geyser/Light That Burns The Sky damage calculation

### PR DESCRIPTION
**Pull request by asgdf**

### CODE REVIEW

**Comment by AustinXII** [comment]
This isn’t correct, “Photon Geyser compares the user's Attack and Special Attack stats, dealing damage to the target using the higher stat.”

**Comment by AustinXII** [comment]
Oh well this is right but I mean can you also try to implement the desc

**Comment by asgdf** [comment]
Alright, now it does the "use Atk or SpA depending on which is higher" thing too. I was initially under the impression that that was already implemented.

**Comment by AustinXII** [comment]
Yeah I forgot to do this, thanks!

**Pull request merged**
