### PR TITLE
Update calculator webpage credits and links

### PR DESCRIPTION
**Pull request by AustinXII**

### CODE REVIEW

**Comment by AustinXII** [comment]
(PR'd so zarel would get notified of the change and can revert if for some reason he doesn't approve of it)

**Comment by Zarel** [comment]
I'm not _very_ happy with this phrasing, but I don't really know how to improve it, so I guess it can stay.

**Comment by AustinXII** [comment]
Which phrasing specifically? We could probably brain storm better phrasing if need be

**Comment by Zarel** [comment]
Also your indentation is bad. :[

**Pull request merged**
