### PR TITLE
Implement protect check

### PR DESCRIPTION
**Pull request by MagiaSN**
Add "Protect" option, if checked, moves without `bypassesProtect` property with do no damage, and z-moves will get their damage reduced
Implement `isZ` as an own property of z-moves instead of adding it dynamically, so even if the user type the z-move themselves, it still works
Move Feint to gen 4 when it was introduced, and change its power in gen 5

### CODE REVIEW

**Comment by AustinXII** [comment]
looks good 👍

**Comment by AustinXII** [comment]
@MagiaSN if you're interested feel free to join the dev room on PS where you'll be given something for your contributions :)

**Comment by MagiaSN** [comment]
@AustinXII Thanks, I think I'm there :)

**Comment by AustinXII** [comment]
@MagiaSN if you see Zarel or me ( I just go by Austin) please pm one of us, I've seem to have just missed you

**Pull request merged**
