### PR TITLE
Improve accessibility for screen readers part 2

### LINKED ISSUE #149: Improve accessibility for screen readers
Similar to [the corresponding issue for the Showdown client](https://github.com/Zarel/Pokemon-Showdown-Client/issues/954). Unfortunately, this will be much harder than the client, as that only needed usability improvements.

* [ ] The generation radio buttons are not recognized as such, they just read as plain text. There is no indication which is selected, or that they are a logical group. Might be because <input> elements need to always be inside a `<form>`, or associated with one using an attribute, so this looks like invalid html5. Similarly for the notation and mode radio buttons on the top, the move selection, single/doubles, terrain selection, weather selection, and spike layers radios.
* [x] What's this used for? `<span id="damageValues">(211, 214, 216, 218, 220, 224, 226, 227, 231, 234, 235, 238, 242, 243, 246, 250)</span>`
* [ ] When the page loads, below pokemon1, I hear "Abomasnow (ORAS NU Mixed Attacker)" being announced as a link. Only by pressing enter do I hear my focus moving into an edit field. I can edit the text, but it doesn't read suggestions when pressing up/down, or announce the presence of suggestions. When I press escape to stop editing, I hear 2 edit boxes now, one of them is probably not meant for editing, so should be `aria-hidden`.
* [x] The crit and z checkboxes are not recognized as such, but read as plain text, with no indication of being checked/unchecked. Similarly, the gravity, stealth rocks, reflect, light screen, protect, leech seed, Foresight, Helping Hand, Friend Guard and Aurora Veil checkboxes. 
* [ ] For controls that can affect either side of the field (e.g, hazards), should be labeled so it differentiates between yours and opponent's side.

### PR DESCRIPTION
**Pull request by Neurrone**
Fixes #149

### CODE REVIEW

**Comment by Zarel** [comment]
I mean, I don't see a huge need to do this all at once? If you prefer it that way, though, I'll leave this open.

**Comment by Neurrone** [comment]
@Zarel thanks, yeah prefer to do it all at once.

**Comment by Neurrone** [comment]
@Zarel ready for review/merging. Could you check particularly that no unintentional UI changes were introduced?

**Comment by Zarel** [comment]
If @AustinXII would like to check it. I personally don't work on the damage calculator and am not familiar with its codebase, so I'm not a good person to review it.

**Comment by Zarel** [comment]
(I merged your other one because the changes were sufficiently superficial that I could understand them eaily)

**Comment by AustinXII** [comment]
I'm not a huge fan of the field selection button layout after this change

**Comment by Neurrone** [comment]
@AustinXII would it suffice to somehow have the column titles hidden?

**Comment by AustinXII** [comment]
@Neurrone that would probably be preferred

**Comment by Neurrone** [comment]
@AustinXII done.

**Comment by AustinXII** [comment]
Looks good, thanks :+1:

**Pull request merged**
