### PR TITLE
TODO List #8

### PR DESCRIPTION
**Pull request by Ntonio36**
Provides a button to clear custom sets once not needed anymore.

### CODE REVIEW

**Comment by AustinXII** [comment]
Rad, screenshot of this?

**Comment by Ntonio36** [comment]
before clearance
Regardless of how likely will you face that kind of Zekrom, all what we care about here is the "Clear Custom Sets" button that shows up instantly as the custom set is added. 

Now after clicking the button, POOF all the sets disappeared, the magic button did its job so it quietly hides back (hence the `display` set to `none` when done, we don't want from it to bloat the HTML). When looking up the custom set of Zekrom we had crafted : 
after
It isn't there anymore.
And by the way, thank you very much for the support, I just try my hardest to be what I'm here for : helping :D.

**Comment by Ntonio36** [comment]
before clearance
Regardless of how legitimate this set is, this is how the page should look like once a custom set has been imported. Notice the "Clear Sets" button that is the pivotal thing in the whole story.

Once clicked, I try again to look for the custom set I've crafted for Zekrom (second image below), aaaand nope, no "Custom Set" appears, it has been deleted successfully, as the alert mentioned when the button was clicked.

Oh, and thanks for the nice word, glad I could help :D.

**Comment by AustinXII** [comment]
This only clears the sets after a refresh. It would be optimal for a refresh to be unneeded but for now this is good

**Comment by AustinXII** [comment]
@Ntonio36 Hmm in the request for this, they wanted specific sets, is that something you could work on as well?

**Comment by Ntonio36** [comment]
I successfully found a way to separately store custom sets all alone, but I couldn't figure out at all how to make them get loaded into the Pokémon name area... That's a TODO I should set for myself, for the least that I can say. But don't expect anything from it, though.

**Comment by AustinXII** [comment]
@Ntonio36 try looking at how customsets is currently done there

**Pull request merged**
