### PR TITLE
Add Future Sight

### PR DESCRIPTION
**Pull request by expl0iter**

### CODE REVIEW

**Comment by Marty-D** [comment]
Future Sight is 80 power in Gen 2, not 120.

**Comment by expl0iter** [comment]
Let me fix when I get home.

**Comment by AustinXII** [comment]
Remember to squash

**Comment by expl0iter** [comment]
@AustinXII I thought GitHub added auto squash thanks for telling me.

**Comment by expl0iter** [comment]
OK it's done lemme just squash it.

**Comment by Marty-D** [comment]
Yeah no need to squash, GitHub has the squash + merge option now. Thanks!

**Pull request merged**
