### PR TITLE
Update dropdown Nature menus with help (e.g.: "Adamant (+Atk/-SpA)")

### PR DESCRIPTION
**Pull request by penpexgit**
I think this could be useful since sometimes for Natures that are not often seen one does not remember well what it does.
And for newbies it's definitely a useful resource, instead of having to check another website in the meantime.
Most other calcs have it, and it saves time at no cost, so here it is.

### CODE REVIEW

**Comment by penpexgit** [comment]
For some reason unknown to me, it seems to now auto-select Mild, instead of Hardy, even though there is still `<option value="Hardy" selected="selected">Hardy</option>`
If anyone has an idea why, I can make the change.

**Comment by penpexgit** [comment]
That's right, and it is also the default behavior currently, not sure why I just didn't realize that.
So yeah everything works fine and when you click a Blank Set, Hardy is still the default as expected.

**Comment by AustinXII** [comment]
Can your scree shot this? I remember I did this at one point but I think the UI looked terrible so I abandoned it

**Comment by penpexgit** [comment]
I think it looks fine, you can see for yourself [here](https://i.imgur.com/aEHnQSc.png) :)

**Comment by AustinXII** [comment]
Thanks!

**Pull request merged**
