### PR TITLE
Update setdex

### PR DESCRIPTION
**Pull request by Honko**
This should also fix the issue with Megas' abilities.

### CODE REVIEW

**Comment by Zarel** [comment]
You know you can merge these yourself, right? Did you want a review or something?

**Comment by Honko** [comment]
Oh cool, forgot I had merge permissions.

**Comment by AustinXII** [comment]
Oh no, I’ve been updating all the analysis’ on smogon and just needed to finish BW. Sorry to hassle you but can you do another one in a week?

**Comment by AustinXII** [comment]
Hence all the new ability properties btw

**Comment by AustinXII** [comment]
Also I believe you just recently got collaborator so don’t worry about not knowing you could just merge yourself

**Comment by Zarel** [comment]
@AustinXII he's always had Collaborator since the day I created this repository...

**Comment by Honko** [comment]
lol, well now I know.

@AustinXII yeah I'll do another one in a couple weeks.

**Comment by AustinXII** [comment]
@Zarel oh lol I swear I seen contributor by his name at some point not like it matters

**Pull request merged**
