### PR TITLE
Ring Target calculation fix

### PR DESCRIPTION
**Pull request by Ntonio36**

### CODE REVIEW

**Comment by AustinXII** [comment]
The code styling needs fixing, also I would have done this differently, why not just check for the defenders item on any of the type effectiveness damage calcs?

**Comment by Ntonio36** [comment]
It would be kind of the same story, since Ring Target denies immunities on moves while moves are single-typed, then that item will only negate one immunity out of 2 immunities theorically possible (since there is no way a Pokémon would be dual-typed Ghost/Ghost for example). Plus, it might not be known if the move type is effective on the other type (let's say Superpower on a Ring Target Sableye, it still is super effective since fighting is x2 on darkness, which shouldn't be ignored), hence the not-so-classy way of `switch`ing through typeEffectivenesses 1 or 2 to check who from them equals 0. I still can make it a traditional if / else if though, just wanted to point my point of view (woah) out.

**Comment by AustinXII** [comment]
Why not just ``if (typeEffectiveness === 0 && defender.item === ‘Ring Target’) { 
typeEffectiveness = 1
}``
?

**Comment by Ntonio36** [comment]
Because as I said, you still have to take into account the move type vs the secondary type of the defender (the type that isn't affected by Ring Target).

**Comment by AustinXII** [comment]
Oh I see, I was misunderstanding. Anyways your code styling needs fixing

**Comment by AustinXII** [comment]
I was thinking it was the same as thousand arrows but they’re different

**Comment by Ntonio36** [comment]
Making it an if else should make it for good, right ?

**Comment by AustinXII** [comment]
Yes this is better but by “styling” I meant your code syntax. You’re missing spaces after ``If`` and before your curly braces

**Comment by Ntonio36** [comment]
The code is implemented and works, the styling has been fixed, what's left ?

**Comment by AustinXII** [comment]
Sorry, thanks for that,  I’m just going to test and make sure this works how intended. Give me a few hours

**Comment by AustinXII** [comment]
Thanks!

**Pull request merged**
