### PR TITLE
Add health bar

### PR DESCRIPTION
**Pull request by Ntonio36**
Adds a little cute health bar that displays how would HP appear, according to the health percent / health amount input.

The only thing I'm not quite sure of would be the color used to the "lower than the half amount" yellow, as well as from which percentage does the bar start turning red.

### CODE REVIEW

**Comment by Zarel** [comment]
Neat! Do you have a screenshot?

**Comment by Zarel** [comment]
<20% is red
<50% is yellow

**Comment by Ntonio36** [comment]
percent
The bar emptied a little bit, but we're still above 50% so the green is still pretty much present.

absolute
You can see the bar adapted itself to the fact of the health being lower than the half, although the yellow is a bit too flashy, I guess.

red

And here is the dying Pokémon on a critical health, when lower than 20% HP.

**Comment by Zarel** [comment]
PS already has health-bar CSS that doesn't look bad. Why don't you take those?

**Comment by Ntonio36** [comment]
I'm not quite sure if the roundy aspect of the health bar fits the calc... But I'll look further on it near the weekend for sure.

**Comment by Ntonio36** [comment]
In the end, I'm okay for taking the PS CSS for the health bar.. but now I need the time to do it. :joy: 

It should be done by the end of the week, hopefully.

**Comment by Zarel** [comment]
lol, that's not remotely a problematic mistake to make, re: estimating times

**Comment by AustinXII** [comment]
@Ntonio36 for future reference ``> =/= >=``

**Pull request merged**
