### PR TITLE
Allow the use of Soul dew on Mega Latias / Mega Latios

### PR DESCRIPTION
**Pull request by AustinXII**
Relevant for OMs

### CODE REVIEW

**Comment by Zarel** [comment]
Maybe you should mark that somehow. "Illegal combination" or "Hackmons only" or something to make it clear it only works on Hackmons-relevant formats.

**Comment by AustinXII** [comment]
@Zarel Updated

**Comment by Zarel** [comment]
Your update doesn't seem to have addressed my concern?

**Comment by AustinXII** [comment]
Note: Won't be updated for a month

**Pull request closed without merging**
