### PR TITLE
Display Speed Calc results

### PR DESCRIPTION
**Pull request by Kiru4**
Speed total is modified by choice scarf and coloured in blue (to mark an item modifying speed total).
FIRST is displayed if the pokemon attacking is faster than the other one.
LAST is displayed if the pokemon attacking is slower (or equal : speed tie) than the other one.

This time you should properly see the diffs.

### CODE REVIEW

**Comment by AustinXII** [comment]
@Kiru4 do you have any intent on squashing?

**Comment by Kiru4** [comment]
I would like the modifications to be integreted into the trunk. Have submitted the commit a while ago...

**Comment by Zarel** [comment]
Your code doesn't fit our code style, and I really don't understand what this is supposed to change. Can you describe the change?

**Comment by Kiru4** [comment]
I did not change your "code style" added function where you added yours etc.
The change allow the user to know which pokemon is faster than the other which is really important.
Plus a pokemon taking an item that changes the value of its statistics display the new statistics values and their display are modified to let the user know the changes.

**Comment by Zarel** [comment]
I'm talking about how you do things like

    if ( STATS[i] == "sp" )
    {

but our code style would be

    if (STATS[i] == 'sp') {

**Comment by AustinXII** [comment]
@Kiru4 the speed is already displayed in battle on PS, I think this PR is kind of pointless

**Comment by Kiru4** [comment]
If the "{" is not placed properly you could easily change it.
@AustinXII I have done it for scarf user and for people building their team to be faster than specifics mons and for people playing on console.

**Comment by Zarel** [comment]
Having looked at this more closely, it doesn't seem like it implements this very efficiently. The UI also seems kind of crude. There's a spot to the right of the stat boost that could be used to represent boosted stats.

Since it would need to be rewritten from scratch before I'd accept it anyway, I'm closing this.

**Comment by Kiru4** [comment]
Ok, hopefully you will do it properly (taking care of the boost + and -), just wanted to help and add features that I needed.

**Pull request closed without merging**
