### PR TITLE
Change Prettier's bracket spacing configuration

### PR DESCRIPTION
**Pull request by scheibo**

### CODE REVIEW

**Comment by Zarel** [comment]
Should we also look at other Prettier configuration?

**Comment by scheibo** [comment]
Not sure I prefer this TBH. It forces you to not use spaces *everywhere*, when I want them sometimes (and yes, I know if we didnt use an automatic formatter that wouldnt be a tradeoff we'd need to discuss). I think in the previous commit they were desirable, but I think on the whole I prefer spaces (ie/ how the code looks before this change). @AustinXII  - what is your preference?

> Should we also look at other Prettier configuration?

I want to turn on consistent quotes in object literals, but thats a different commit IMO

**Comment by Zarel** [comment]
Okay, the other defaults make sense to me.

**Comment by Zarel** [comment]
> I want to turn on consistent quotes in object literals, but thats a different commit IMO.

I'd generally disagree, unless we're talking about different things?

**Comment by scheibo** [comment]
> I'd generally disagree, unless we're talking about different things?

Another 'it depends'. But for an object with like only 10 keys and 2 have to be quoted it bugs me that the rest arent consistent. Also, remember - this is automatically enforced so people editing the file can just forget quotes and then run `npm run fix` (or forget to and have to followup with shameful commits after the fact...)

**Pull request merged**
